// Code generated by PromptDSL.
package main

import (
	   gen "workflow/generated"
	   "log"
)
func main() {
    //在此组织工作流
    input :=gen.SplitSolutionStepsInputContext{
		Process:"通过研究学生的学习行为，心理学家发现，学生接受能力依赖于老师引入概念和描述问题所用的时间，讲座开始时，学生的兴趣增长，中间有一段不太长的时间，学生的兴趣保持理想的状态，随后学生注意力开始分散．分析结果和实验表明，用f（x）表示学生掌握和接受概念的能力（f（x）值越大，表示接受能力越强），x表示提出和讲授概念的时间（单位：分），可以有以下的公式：\n$$f(x) = \\begin{cases} -0.1x^2 + 2.6x + 43 & (0 < x \\le 10) \\\\ 59 & (10 < x \\le 16) \\\\ -3x + 107 & (16 < x \\le 30) \\end{cases}$$\n（1）开讲多少分钟后，学生的接受能力最强？能维持多少时间？\n（2）开讲5分钟与开讲20分钟比较，学生的接受能力何时强一些？",
		Question:"解：（1）当$0＜x≤10$时，$f(x)=-0.1x^2+2.6x+43$，\n为开口向下的二次函数，对称轴为$x=13$，\n故$f(x)$的最大值为$f(10)=59$，\n当$10＜x≤16$时，$f(x)=59$，\n当$x＞16$时，$f(x)$为减函数，且$f(x)＜59$，\n因此，开讲10分钟后，学生达到最强接受能力（为59），能维持6分钟时间．\n（2）$f(5)=53.5$，$f(20)=47$，\n故开讲5分钟时学生的接受能力比开讲20分钟时要强一些．",
	}
	ret1,err:=gen.SplitSolutionSteps(input)
	if err!=nil{
		log.Println(err)
	}
	// ret2:=gen.CheckAndCompleteStepConditions(ret1)
	log.Println(ret1)
}
