// Code generated by PromptDSL. DO NOT EDIT.
package main

import (
	"os"
	"log"
	"fmt"
	"strings"
	"github.com/ycstella/prompt-dsl/service"
	"github.com/ycstella/prompt-dsl/codegen"
	"github.com/ycstella/prompt-dsl/config"
	"encoding/json"
	"path/filepath"
	"time"
	"github.com/ycstella/prompt-dsl/utils"
)

type GetpathSolution struct {
    Step int `json:"Step"`
    SolutionContent string `json:"SolutionContent"`
}

type GetpathProcess struct {
    Id int `json:"Id"`
    Question string `json:"Question"`
    Solution GetpathSolution `json:"Solution"`
    Dificulty int `json:"Dificulty"`
}

type GetpathFromePhenomena struct {
    Phenomenon string `json:"Phenomenon"`
    Projection string `json:"Projection"`
    Concept string `json:"Concept"`
    IsDerived string `json:"IsDerived"`
}

type GetpathPath struct {
    FromePhenomena GetpathFromePhenomena `json:"FromePhenomena"`
    Expression string `json:"Expression"`
    ToPhenomena GetpathFromePhenomena `json:"ToPhenomena"`
}

type GetpathInputContext struct {
    Process GetpathProcess `json:"Process"`
}

type GetpathOutputContext struct {
    Id int `json:"Id"`
    Path GetpathPath `json:"Path"`
}

type GetpathModelOutputContext struct {
    Id int `json:"Id"`
    Path GetpathPath `json:"Path"`
}

type Getpath struct {
    Input []GetpathInputContext
    Output GetpathOutputContext
    ModelOutput GetpathModelOutputContext
	config      string
	modelname      string
	inputfile      string
	modelRet      string
	currentData      GetpathInputContext
	data      []byte
	path      string
	fixRet      GetpathModelOutputContext
	afterRet      GetpathOutputContext
	results []any
}

func NewGetpath() *Getpath {
	return &Getpath{
		config:    config.WF.Config,
		modelname: config.WF.Model,
		inputfile: config.WF.Input,
		path: "",
	}
}

func (p *Getpath) init() {
	// 初始化配置和日志
	if len(os.Args) < 3 {
		log.Fatal("请提供输入文件路径和配置路径作为参数")
	}
	log.Println(os.Stderr, "[main] 程序启动，等待输入...")
	config.InitConfig(p.config)
	config.InitLogger()
}

func (p *Getpath) loadInput() {
	// 读取输入文件
	var err error
	p.data, err = os.ReadFile(p.inputfile)
	if err != nil {
		log.Fatalf("无法读取文件: %v", err)
	}
}

func (p *Getpath) parsedata() {
	if err := json.Unmarshal(p.data, &p.Input); err == nil {
		return
	}

	var single GetpathInputContext
	if err := json.Unmarshal(p.data, &single); err == nil {
		p.Input = []GetpathInputContext{single}
		return
	}

	log.Fatalf("输入 JSON 格式无效")
}

func (p *Getpath) writeOut(newResult any) {
    exePath, err := os.Executable()
    if err != nil {
        log.Fatalf("获取可执行文件路径失败: %v", err)
    }
    exeDir := filepath.Dir(exePath)
    outputPath := filepath.Join(exeDir, "output.json")
    p.results = append(p.results, newResult)
    output, err := json.MarshalIndent(p.results, "", "  ")
    if err != nil {
        log.Fatalf("结果序列化失败: %v", err)
    }
    err = os.WriteFile(outputPath, output, 0644)
    if err != nil {
        log.Fatalf("写入输出文件失败: %v", err)
    }
    log.Println("结果已写入 output.json 文件")
}
func (p *Getpath)GenSys(in GetpathInputContext) string {
    var b strings.Builder
    b.WriteString("你是一位精通小学数学的优秀教师，能够很好地从解题过程中提取出现象 \n")
    return b.String()

}

func (p *Getpath)GenUser(in GetpathInputContext) string {
    var b strings.Builder
    b.WriteString("要求：\n")
    b.WriteString("1.**FromePhenomena**:指支撑当前过程推导所需要的前提条件\n")
    b.WriteString("必须结合题目的具体语境来表述，而不是抽象的公式复述，也非仅数学转换结果。\n")
    b.WriteString("需包含`Phenomenon`（现象）、`Projection`（对应的映射或数学表达）、`Concept`（涉及的概念）、`IsDerived`（是否为推导结论）  \n")
    b.WriteString("原题给出的信息 IsDerived=false，推导得到的信息 IsDerived=true。\n")
    b.WriteString("**FromePhenomena** 不仅包含直接用到的条件，也必须包含 与题目结论相关的隐含条件，例如工作总量、单位、任务对象等，只要对 ToPhenomena 的语境成立是必需的。 \n")
    b.WriteString("2.**Expression**：表示当前过程所使用的**通用公式、转换规则或推理方法**，不包含具体数值计算，只写成适用于类似问题的抽象表达式。\n")
    b.WriteString("3.**ToPhenomena**：指通过该步骤得到的新的结论。  \n")
    b.WriteString("**必须结合题目的具体语境来表述**，而不是抽象的公式复述，也非仅数学转换结果。  \n")
    b.WriteString("Phenomenon 要体现题目中的对象、条件或场景。  \n")
    b.WriteString("Projection 清晰表述该结论在题目中的意义，需明确主体、量和数值。  \n")
    b.WriteString("Concept 使用与题目语境相关的概念。  \n")
    b.WriteString("IsDerived=true \n")
    b.WriteString("4. 其他规则：\n")
    b.WriteString("禁止遗漏关键依赖条件；\n")
    b.WriteString("需要注意隐藏条件，例如工作总量等\n")
    b.WriteString("题目为：\n")
    b.WriteString(string(utils.MustJSON(in.Process.Question)) + "\n")
    b.WriteString("需要提取的过程为：\n")
    b.WriteString(string(utils.MustJSON(in.Process.Solution)) + "\n")
    b.WriteString("示例如下：\n")
    b.WriteString("题目为：一项工程，甲 3 天可以完成工程总量的 1/3，乙完成工程总量的 1/4 要 3 天。现由甲先单独做 2 天，剩下的由乙单独做，乙还要做几天才能完成任务？\n")
    b.WriteString("需要拆分的过程为：乙的工作效率是：\n")
    b.WriteString("$$\n")
    b.WriteString("\frac{1/4}{3} = \frac{1}{12} \\quad \text{（即乙每天完成工程的 } \frac{1}{12} \text{）}\n")
    b.WriteString("$$\n")
    b.WriteString("该题已得到的Phenomenon及其对应的Projection如下\n")
    b.WriteString("Phenomenon：甲 3 天可以完成工程总量的 1/3，Projection：甲3天的工作量为1/3\n")
    b.WriteString("Phenomenon：一项工程，Projection：工作总量为1\n")
    b.WriteString("Phenomenon：甲 3 天可以完成工程总量的 1/3，Projection：甲工作量为1/3的工作时间为3天\n")
    b.WriteString("Phenomenon：甲单独完成这份工作需要9天，Projection：甲的工作效率为1/9\n")
    b.WriteString("返回结果为：\n")
        b.WriteString("```json\n")
    b.WriteString("{\n")
    b.WriteString("    \"Id\": 0  // ,\n")
    b.WriteString("    \"Path\": {  // \n")
    b.WriteString("        \"FromePhenomena\": {  // \n")
    b.WriteString("            \"Phenomenon\": \"\"  // ,\n")
    b.WriteString("            \"Projection\": \"\"  // ,\n")
    b.WriteString("            \"Concept\": \"\"  // ,\n")
    b.WriteString("            \"IsDerived\": \"\"  // \n")
    b.WriteString("        },\n")
    b.WriteString("        \"Expression\": \"\"  // ,\n")
    b.WriteString("        \"ToPhenomena\": {}  // \n")
    b.WriteString("    }\n")
    b.WriteString("}\n")
    b.WriteString("```\n")

    return b.String()

}

func (p *Getpath)AfterProcess() error {

        p.afterRet.Path=p.fixRet.Path
        return nil
    
}

func (p *Getpath)FixProcess() error{
	var err error
	p.fixRet,err=codegen.FixAuto[GetpathModelOutputContext](p.modelRet)
	return err

}
func (p *Getpath)ValidateInput(input GetpathInputContext) (error){
	if  p.currentData.Process == (GetpathProcess{}) {
		return fmt.Errorf("GetpathInputContext:Process 不能为空")
	}
    return nil
}
func (p *Getpath) runWithRetry(maxRetries int) error {
    var err error
    for attempt := 1; attempt <= maxRetries; attempt++ {
        err = p.run()
        if err == nil {
            return nil
        }
        log.Printf("调用模型失败，第 %d 次重试: %v", attempt, err)
        time.Sleep(time.Second * 2)
    }
    return fmt.Errorf("调用模型失败，已重试 %d 次仍然出错: %v", maxRetries, err)
}

func (p *Getpath)run() error {
   log.Println("run")
    var err error
    err=p.ValidateInput(p.currentData)
    if err!=nil {
    	return err
    }
    sys := p.GenSys(p.currentData)
    user := p.GenUser(p.currentData)
    modelConfig := config.GetModelConfig(p.modelname)
    llm := service.NewLLMClient(*modelConfig)
    if modelConfig.Stream  {
        // 流式模式，直接输出，不做 JSON 解析
        _, err := llm.GeneratePromptResponse(sys, user, true)
        if err != nil {
            log.Println(os.Stderr, "调用大模型失败: %v\n", err)
            os.Exit(1)
        }
        return nil
    } else {
        // 非流式模式，拿完整结果再处理
        log.Println("sys:",sys)
        log.Println("user:",user)
        p.modelRet,err= llm.GeneratePromptResponse(sys, user, false)
        log.Println("模型回复:",p.modelRet)
        if err != nil {
            log.Println(os.Stderr, "调用大模型失败: %v\n", err)
            os.Exit(1)
        }
        err = p.FixProcess()
        if err != nil {
            log.Println(os.Stderr, "解析输入 JSON 失败011111: %v\n", err)
            os.Exit(1)
        }
        err = p.AfterProcess()
        encoded, err := json.Marshal(p.afterRet)
        if err != nil {
            log.Println(os.Stderr, "输出编码失败: %v\n", err)
            os.Exit(1)
        }
        log.Println(string(encoded))
        return err
        }
    }
func (p *Getpath) singleExecute() {
	err := p.runWithRetry(3)
	if err != nil {
		log.Println("p.run失败：", err)
	}
}
