// Code generated by WorkflowDSL Generator. DO NOT EDIT.

package main
import (
	"log"
	"io/ioutil"
	// "github.com/ycstella/prompt-dsl/codegen"
	// "github.com/spf13/cast"
	"github.com/ycstella/prompt-dsl/config"
	"os"
	"encoding/json"
	"fmt"
)




type In1 struct {
    Id int
    Question string
    Answer string
}



type FromePhenomena struct {
    Phenomenon string
    Projection string
    Concept string
    IsDerived string
}

type Path struct {
    FromePhenomena FromePhenomena
    Expression string
    ToPhenomena FromePhenomena
}

type Solution struct {
    Step int
    SolutionContent string
    Path Path
}

type Process struct {
    Id int
    Question string
    Solution Solution
    Dificulty int
}

type Out struct {
    Id int
    Question string
    Process Process
}



  
func WExtractSteps(v2 any) (result Process) { 
	task:= NewExtractSteps()
	task.init()
	err := ConvertStruct(v2,&task.currentData)
	if err != nil { 
		log.Fatal(err)
	}
	task.singleExecute()
	err = ConvertStruct(task.afterRet.Process, &result)
	if err != nil {
		log.Println("结果转换失败：", err)
		return Process{}
	}
	return result 	//返回值精确一点就ok(参数值也一样)
}  
func WGetpath(v5 any) (result Path) { 
	task:= NewGetpath()
	task.init()
	err := ConvertStruct(v5,&task.currentData.Process)
	if err != nil { 
		log.Fatal(err)
	}
	task.singleExecute()
	err = ConvertStruct(task.afterRet.Path, &result)
	if err != nil {
		log.Println("结果转换失败：", err)
		return Path{}
	}
	return result 	//返回值精确一点就ok(参数值也一样)
}


func Run(In1 In1) Out {
    // 执行依赖计算

	// 拓扑排序执行
		v1 := In1.Id
		v2 := In1
		v3 := In1.Question
		v5 := WExtractSteps(v2)
		v12 := WGetpath(v5)

	//字段赋值
	var out Out
	out.Id = v1
	out.Question = v3
	//	out.Process = v5
	out.Process.Id = v1
	out.Process.Question = v3
	//	out.Process.Solution = v5.Solution
	out.Process.Solution.Step = v5.Solution.Step
	out.Process.Solution.SolutionContent = v5.Solution.SolutionContent
	//	out.Process.Solution.Path = v12
	//	out.Process.Solution.Path.FromePhenomena = v12.FromePhenomena
	out.Process.Solution.Path.FromePhenomena.Phenomenon = v12.FromePhenomena.Phenomenon
	out.Process.Solution.Path.FromePhenomena.Projection = v12.FromePhenomena.Projection
	out.Process.Solution.Path.FromePhenomena.Concept = v12.FromePhenomena.Concept
	out.Process.Solution.Path.FromePhenomena.IsDerived = v12.FromePhenomena.IsDerived
	out.Process.Solution.Path.Expression = v12.Expression
	out.Process.Solution.Path.ToPhenomena = v12.ToPhenomena
	out.Process.Dificulty = v5.Dificulty
    return out
}



func main() {
	fmt.Println("workflow执行ing")
	inputFile := os.Args[1]
	b, err := ioutil.ReadFile(inputFile)
	if err != nil {
		log.Fatalf("读取文件失败: %v", err)
	}
	config.WF.Model = "gemini-2.0-flash"
	config.WF.Config = "."
	var in In1
	
	json.Unmarshal(b,&in)
	fmt.Println("收到输入: ", in)
	log.Printf("收到输入: %+v\n", in)
	out := Run(in)
	fmt.Println("workflow执行44444444")
	// 输出 JSON 结果
	result, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		log.Fatalf("结果序列化失败: %v", err)
	}
	fmt.Println(string(result))
}


func ConvertStruct[A any, B any](src A, dst *B) error {
	data, err := json.Marshal(src)
	if err != nil {
		return fmt.Errorf("marshal error: %w", err)
	}
	if err := json.Unmarshal(data, dst); err != nil {
		return fmt.Errorf("unmarshal error: %w", err)
	}
	return nil
}
