package codegen

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
)

var symbolToImport = map[string]string{
	// 基础功能
	"fmt.":          "fmt",
	"strings.":      "strings",
	"strconv.":      "strconv",
	"bytes.":        "bytes",
	"math.":         "math",
	"math/rand.":    "math/rand",
	"time.":         "time",
	"unicode.":      "unicode",
	"unicode/utf8.": "unicode/utf8",
	"json":          "encoding/json",

	// IO 与文件
	"io.":            "io",
	"io/ioutil.":     "io/ioutil", // 旧版兼容，Go 1.16 后用 os.ReadFile 等替代
	"os.":            "os",
	"path.":          "path",
	"path/filepath.": "path/filepath",

	// 网络与编码
	"net.":             "net",
	"net/http.":        "net/http",
	"net/url.":         "net/url",
	"encoding/json.":   "encoding/json",
	"encoding/xml.":    "encoding/xml",
	"encoding/base64.": "encoding/base64",
	"encoding/hex.":    "encoding/hex",

	// 日志与调试
	"log.":      "log",
	"debug/pe.": "debug/pe", // 示例：用于调试工具

	// 并发与同步
	"sync.":        "sync",
	"sync/atomic.": "sync/atomic",
	"context.":     "context",

	// 正则与错误处理
	"regexp.": "regexp",
	"errors.": "errors",

	// 反射与运行时
	"reflect.":       "reflect",
	"runtime.":       "runtime",
	"runtime/debug.": "runtime/debug",

	// 测试（如果是生成测试代码时）
	"testing.": "testing",

	// 数据结构与容器
	"container/list.": "container/list",
	"container/heap.": "container/heap",
}

type CodeBuilder struct {
	promptNode    *PromptNode
	fileName      string
	b             strings.Builder
	outputTypeStr string
	model         string
	path string
	goimport     []goimport
	genPrompCode *final
	outname      string
	output       string
	loopClass    string
	loopName     string
}

func NewCodeBuilder(p *PromptNode, fileName string, g *final) *CodeBuilder {
	var b strings.Builder
	loopName := p.iteraterPath
	parts := strings.Split(loopName, ".")
	last := parts[len(parts)-1] // 取最后一部分
	return &CodeBuilder{
		promptNode:   p,
		fileName:     fileName,
		b:            b,
		goimport:     p.Goimport,
		genPrompCode: g,
		loopName:     last,
		path: p.iteraterPath,
	}
}

// output为数组的处理
func (c *CodeBuilder) isArray() error {
	// fmt.Println("😅")
	if len(c.promptNode.ModelFields) > 0 {
		fmt.Println("root.ModelFields:", c.promptNode.ModelFields)
	}
	c.outputTypeStr = c.fileName + "OutputContext"
	if c.promptNode.outputspectNodes.IsArray {
		c.outputTypeStr = "[]" + c.fileName + "OutputContext"
	}
	if len(c.promptNode.OutFields) == 0 {
		c.outputTypeStr = "[]string"
	}
	if len(c.promptNode.ModelFields) > 0 {
		c.model = c.fileName + "ModelOutputContext"
		if c.promptNode.outputspectNodes.IsArray {
			c.model = "[]" + c.fileName + "ModelOutputContext"
		}
	}
	return nil
}

// 写包名和注释
func (c *CodeBuilder) writeGeneratedHeader() error {

	c.b.WriteString("// Code generated by PromptDSL. DO NOT EDIT.\n")
	c.b.WriteString(fmt.Sprintf("package %s\n\n", "main"))
	return nil
}

// 写入import
func (c *CodeBuilder) buildImport() error {
	//after+fix
	afterCode := strings.Join(c.promptNode.AfterCode, "\n")
	fixCode := strings.Join(c.promptNode.FixCode, "\n")
	beforeCode := strings.Join(c.promptNode.BeforeCode, "\n")

	allCode := afterCode + "\n" + fixCode + "\n" + beforeCode
	// renderImportSectionWithAlias()
	pkgs := inferImportsFromCode(allCode)
	//main
	requiredPkgs := []string{"os", "log", "fmt", "strings", "github.com/ycstella/prompt-dsl/service", "github.com/ycstella/prompt-dsl/codegen", "github.com/ycstella/prompt-dsl/config", "encoding/json", "path/filepath", "time"}
	if len(c.promptNode.FixCode) == 0 || len(c.promptNode.AfterCode) == 0 {
		requiredPkgs = []string{"os", "log", "fmt", "github.com/ycstella/prompt-dsl/service", "strings", "github.com/ycstella/prompt-dsl/config", "encoding/json", "path/filepath"}
	}
	if strings.TrimSpace(c.promptNode.FixCode[0]) == "" && strings.TrimSpace(c.promptNode.AfterCode[0]) == "" {
		requiredPkgs = []string{"os", "log", "fmt", "github.com/ycstella/prompt-dsl/service", "strings", "github.com/ycstella/prompt-dsl/config", "encoding/json", "path/filepath", "time", "github.com/ycstella/prompt-dsl/codegen"}
	}
	if len(c.promptNode.RunExe) > 0 {
		requiredPkgs = append(requiredPkgs, "os/exec")
	}
	if c.loopName != "" {
		requiredPkgs = append(requiredPkgs, "reflect")
	}
	for _, req := range requiredPkgs {
		has := false
		for _, pkg := range pkgs {
			if pkg == req {
				has = true
				break
			}
		}
		if !has {
			pkgs = append(pkgs, req)
		}
	}
	importBlock := renderImportSectionWithAlias(c.goimport, pkgs)

	c.b.WriteString(importBlock)
	return nil
}
func (c *CodeBuilder) buildPromptStruct() error {
	c.b.WriteString("type " + c.fileName + " struct {\n")
	c.b.WriteString("    Input []" + c.fileName + "InputContext\n")
	if len(c.promptNode.OutFields) > 0 {
		c.b.WriteString("    Output " + c.fileName + "OutputContext\n")
	}

	if len(c.promptNode.ModelFields) > 0 {
		c.b.WriteString("    ModelOutput " + c.fileName + "ModelOutputContext\n")
	}
	c.b.WriteString("\tconfig      string\n")
	c.b.WriteString("\tmodelname      string\n")
	c.b.WriteString("\tinputfile      string\n")
	c.b.WriteString("\tmodelRet      string\n")
	c.b.WriteString("\tcurrentData      " + c.fileName + "InputContext\n")
	c.b.WriteString("\tdata      []byte\n")
	c.b.WriteString("\tpath      string\n")
	c.b.WriteString("\tfixRet      " + c.model + "\n")
	c.b.WriteString("\tafterRet      " + c.outputTypeStr + "\n")
	if c.promptNode.iteraterPath != "" {
		c.b.WriteString("\tit      " + c.loopClass + "\n")
		c.b.WriteString("\tit_idx      int\n")
	}
	c.b.WriteString("\tresults []any\n")
	c.b.WriteString("}\n\n")
	return nil
}
func (c *CodeBuilder) subStruct() {
	for _, substruct := range c.promptNode.SubFields {
		c.b.WriteString("type " + c.fileName + capitalizeFirst(substruct.Name) + " struct {\n")
		for _, field := range substruct.Fields {
			c.buildField(field)
		}
		c.b.WriteString("}\n\n")
	}
}

func (c *CodeBuilder) buildInputContext() {
	c.b.WriteString("type " + c.fileName + "InputContext struct {\n")
	for _, field := range c.promptNode.InFields {
		c.buildField(field)
	}
	c.b.WriteString("}\n\n")
}
func (c *CodeBuilder) buildField(field FieldDef) {
	fieldName := capitalizeFirst(field.Name)
	if field.Name == c.loopName {
		c.loopClass = c.fileName + fieldName
	}
	if field.Type == "struct" {
		c.b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, c.fileName+fieldName, field.JsonName))
		return
	}
	if field.Type == "[]struct" {
		c.b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, "[]"+c.fileName+fieldName, field.JsonName))
		return
	}
	c.b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, field.Type, field.JsonName))
}

func (c *CodeBuilder) buildOutputContext() {
	if len(c.promptNode.OutFields) > 0 {
		c.b.WriteString("type " + c.fileName + "OutputContext struct {\n")
		for _, field := range c.promptNode.OutFields {
			skip := false
			for _, ann := range field.Annotations {
				if ann == "outignore" {
					skip = true
					break
				}
			}
			// log.Println(field.Annotations)
			if skip {
				continue
			}
			c.buildField(field)
		}
		c.b.WriteString("}\n\n")
	}
}
func (c *CodeBuilder) buildModelOutputContext() {
	if len(c.promptNode.ModelFields) > 0 {
		c.b.WriteString("type " + c.fileName + "ModelOutputContext struct {\n")
		for _, field := range c.promptNode.ModelFields {
			c.buildField(field)
		}
		c.b.WriteString("}\n\n")
	}
}
func (c *CodeBuilder) buildstruct() error {
	c.subStruct()
	c.buildInputContext()
	c.buildOutputContext()
	c.buildModelOutputContext()
	c.buildPromptStruct()
	return nil
}
func (c *CodeBuilder) genModelPrompt() error {
	//gensystem
	//写入sys处理逻辑
	if c.loopClass != "" {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")GenSys(in " + c.fileName + "InputContext,it " + c.loopClass + ") string {\n"))
	} else {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")GenSys(in " + c.fileName + "InputContext) string {\n"))
	}
	c.b.WriteString("    var b strings.Builder\n")

	for _, line := range c.genPrompCode.Sys {
		c.b.WriteString(fmt.Sprintf("    %s\n", line))
	}
	c.b.WriteString("    return b.String()\n")
	c.b.WriteString("\n}\n\n")

	//genuser
	if c.loopClass != "" {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")GenUser(in " + c.fileName + "InputContext,it " + c.loopClass + ") string {\n"))
	} else {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")GenUser(in " + c.fileName + "InputContext) string {\n"))
	}
	c.b.WriteString("    var b strings.Builder\n")

	for _, line := range c.genPrompCode.User {
		c.b.WriteString(fmt.Sprintf("    %s\n", line))
	}
	c.b.WriteString("    return b.String()\n")
	c.b.WriteString("\n}\n\n")
	return nil
}

// model or output
func (c *CodeBuilder) ifModel() error {

	c.output = c.outputTypeStr
	c.outname = "output"
	if len(c.promptNode.ModelFields) > 0 {
		c.output = c.model
		c.outname = "model"
	}
	return nil
}

func (c *CodeBuilder) writeNew() error {
	// 拼接函数签名
	c.b.WriteString("func New" + c.fileName + "() *" + c.fileName + " {\n")
	c.b.WriteString("\treturn &" + c.fileName + "{\n")
	// 拼接各字段初始化
	c.b.WriteString("\t\tconfig:    os.Args[2],\n")
	c.b.WriteString("\t\tmodelname: os.Args[1],\n")
	c.b.WriteString("\t\tinputfile: os.Args[3],\n")
	c.b.WriteString("\t\tpath: \""+c.path+"\",\n")

	c.b.WriteString("\t}\n") // 关闭结构体
	c.b.WriteString("}\n\n") // 关闭函数

	return nil
}
func (c *CodeBuilder) writeInit() error {
	c.b.WriteString("func (p *" + c.fileName + ") init() {\n")
	c.b.WriteString("\t// 初始化配置和日志\n")
	c.b.WriteString("\tif len(os.Args) < 3 {\n")
	c.b.WriteString("\t\tlog.Fatal(\"请提供输入文件路径和配置路径作为参数\")\n")
	c.b.WriteString("\t}\n")
	c.b.WriteString("\tlog.Println(os.Stderr, \"[main] 程序启动，等待输入...\")\n")
	c.b.WriteString("\tconfig.InitConfig(p.config)\n")
	c.b.WriteString("\tconfig.InitLogger()\n")
	c.b.WriteString("}\n\n")
	return nil
}
func (c *CodeBuilder) writeLoadInput() error {
	c.b.WriteString("func (p *" + c.fileName + ") loadInput() {\n")
	c.b.WriteString("\t// 读取输入文件\n")
	c.b.WriteString("\tvar err error\n")
	c.b.WriteString("\tp.data, err = os.ReadFile(p.inputfile)\n")
	c.b.WriteString("\tif err != nil {\n")
	c.b.WriteString("\t\tlog.Fatalf(\"无法读取文件: %v\", err)\n")
	c.b.WriteString("\t}\n")
	c.b.WriteString("}\n\n")
	return nil
}
func (c *CodeBuilder) writeParseData() error {
	c.b.WriteString("func (p *" + c.fileName + ") parsedata() {\n")

	c.b.WriteString("\tif err := json.Unmarshal(p.data, &p.Input); err == nil {\n")
	c.b.WriteString("\t\treturn\n")
	c.b.WriteString("\t}\n\n")

	c.b.WriteString("\tvar single " + c.fileName + "InputContext" + "\n") // c.inputType = "SplitSolutionStepsInputContext"
	c.b.WriteString("\tif err := json.Unmarshal(p.data, &single); err == nil {\n")
	c.b.WriteString("\t\tp.Input = []" + c.fileName + "InputContext" + "{single}\n")
	c.b.WriteString("\t\treturn\n")
	c.b.WriteString("\t}\n\n")

	// JSON 格式无效报错
	c.b.WriteString("\tlog.Fatalf(\"输入 JSON 格式无效\")\n")

	// 函数结束
	c.b.WriteString("}\n\n")
	return nil
}
func (c *CodeBuilder) buildWriteOut() error {
	c.b.WriteString("func (p *" + c.fileName + ") writeOut(newResult any) {\n")
	c.b.WriteString("    exePath, err := os.Executable()\n")
	c.b.WriteString("    if err != nil {\n")
	c.b.WriteString("        log.Fatalf(\"获取可执行文件路径失败: %v\", err)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    exeDir := filepath.Dir(exePath)\n")
	c.b.WriteString("    outputPath := filepath.Join(exeDir, \"output.json\")\n")
	c.b.WriteString("    p.results = append(p.results, newResult)\n")
	c.b.WriteString("    output, err := json.MarshalIndent(p.results, \"\", \"  \")\n")
	c.b.WriteString("    if err != nil {\n")
	c.b.WriteString("        log.Fatalf(\"结果序列化失败: %v\", err)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    err = os.WriteFile(outputPath, output, 0644)\n")
	c.b.WriteString("    if err != nil {\n")
	c.b.WriteString("        log.Fatalf(\"写入输出文件失败: %v\", err)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    log.Println(\"结果已写入 output.json 文件\")\n")
	c.b.WriteString("}\n")
	return nil
}

func (c *CodeBuilder) writeBefore() error {

	if strings.TrimSpace(c.promptNode.BeforeCode[0]) != "" {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")Before() error{\n"))
		c.b.WriteString(c.promptNode.BeforeCode[0])
		c.b.WriteString("\n}\n")
	}
	return nil
}
func (c *CodeBuilder) writeAfter() error {

	if strings.TrimSpace(c.promptNode.AfterCode[0]) != "" {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")AfterProcess() error {\n"))
		c.b.WriteString(c.promptNode.AfterCode[0])
		c.b.WriteString("\n}\n\n")
	} else {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")AfterProcess() error{\n"))
		c.b.WriteString("\t//没有后处理函数时自动调用\n")
		c.b.WriteString("\treturn nil\n")
		c.b.WriteString("\n}\n")
	}
	return nil
}
func (c *CodeBuilder) writeFix() error {
	log.Println("fixcode是否为空：", c.promptNode.FixCode[0], "seugu")
	if strings.TrimSpace(c.promptNode.FixCode[0]) != "" {
		fixauto := "codegen.FixLatex[" + c.output + "](p.modelRet)\n"
		re := regexp.MustCompile(`fix-latex`)
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")FixProcess() error{\n"))
		c.b.WriteString(re.ReplaceAllString(c.promptNode.FixCode[0], fixauto))
		c.b.WriteString("\n}\n")
	} else {
		c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")FixProcess() error{\n"))
		c.b.WriteString("\tvar err error\n")
		c.b.WriteString("\tp.fixRet,err=codegen.FixAuto[" + c.output + "](p.modelRet)\n")
		c.b.WriteString("\treturn err\n")
		c.b.WriteString("\n}\n")
	}
	return nil
}
func (c *CodeBuilder) buildIsValid() error {
	c.b.WriteString(fmt.Sprintf("func (p *" + c.fileName + ")ValidateInput(input " + c.fileName + "InputContext) (error){\n"))
	// fmt.Println("derived:👀")
	for _, f := range c.promptNode.InFields {
		// 如果包含 "derived" 注解，则跳过校验
		skip := false
		for _, ann := range f.Annotations {
			// fmt.Println("derived:👀", ann)
			if ann == "derived" {
				skip = true
				break
			}
		}
		if skip {
			continue
		}

		switch f.Type {
		case "string":
			c.b.WriteString(fmt.Sprintf(
				"\tif  p.currentData.%s == \"\" {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, c.fileName, f.Name))
		case "struct":
			c.b.WriteString(fmt.Sprintf(
				"\tif  p.currentData.%s == ("+c.fileName+"%s{}) {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, f.Name, c.fileName, f.Name))
		case "int", "int32", "int64", "float32", "float64":
			c.b.WriteString(fmt.Sprintf(
				"\tif  p.currentData.%s == 0 {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, c.fileName, f.Name))
		case "[]string", "[]int", "[]float64", "map[string]string":
			c.b.WriteString(fmt.Sprintf(
				"\tif len( p.currentData.%s) == 0 {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, c.fileName, f.Name))
		}
	}
	c.b.WriteString("    return nil\n}\n")
	return nil
}

func (c *CodeBuilder) buildExecutePipeline() error {
	c.b.WriteString("\nfunc (p *" + c.fileName + ")run() error {\n")
	c.b.WriteString("   log.Println(\"run\")\n")
	c.b.WriteString("    var err error\n")
	c.b.WriteString("    err=p.ValidateInput(p.currentData)\n")
	c.b.WriteString("    if err!=nil {\n")
	c.b.WriteString("    \treturn err\n")
	c.b.WriteString("    }\n")

	//before
	if strings.TrimSpace(c.promptNode.BeforeCode[0]) != "" {
		c.b.WriteString("    err=p.Before()\n")
		c.b.WriteString("    if err!=nil {\n")
		c.b.WriteString("    \tlog.Println(os.Stderr, \"预处理失败 %v\", err)\n")
		c.b.WriteString("    \tos.Exit(1)\n")
		c.b.WriteString("    }\n")
	}
	if c.loopClass != "" {
		c.b.WriteString("    sys := p.GenSys(p.currentData,p.it)\n")
		c.b.WriteString("    user := p.GenUser(p.currentData,p.it)\n")
	} else {
		c.b.WriteString("    sys := p.GenSys(p.currentData)\n")
		c.b.WriteString("    user := p.GenUser(p.currentData)\n")
	}
	c.b.WriteString("    modelConfig := config.GetModelConfig(p.modelname)\n")
	c.b.WriteString("    llm := service.NewLLMClient(*modelConfig)\n")

	c.b.WriteString("    if modelConfig.Stream  {\n")
	c.b.WriteString("        // 流式模式，直接输出，不做 JSON 解析\n")
	c.b.WriteString("        _, err := llm.GeneratePromptResponse(sys, user, true)\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(os.Stderr, \"调用大模型失败: %v\\n\", err)\n")
	c.b.WriteString("            os.Exit(1)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        return nil\n")
	c.b.WriteString("    } else {\n")
	c.b.WriteString("        // 非流式模式，拿完整结果再处理\n")
	c.b.WriteString("        log.Println(\"sys:\",sys)\n")
	c.b.WriteString("        log.Println(\"user:\",user)\n")
	c.b.WriteString("        p.modelRet,err= llm.GeneratePromptResponse(sys, user, false)\n")
	c.b.WriteString("        log.Println(\"模型回复:\",p.modelRet)\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(os.Stderr, \"调用大模型失败: %v\\n\", err)\n")
	c.b.WriteString("            os.Exit(1)\n")
	c.b.WriteString("        }\n")

	if len(c.promptNode.OutFields) > 0 {
		c.b.WriteString("        err = p.FixProcess()\n")
		c.b.WriteString("        if err != nil {\n")
		c.b.WriteString("            log.Println(os.Stderr, \"解析输入 JSON 失败011111: %v\\n\", err)\n")
		c.b.WriteString("            os.Exit(1)\n")
		c.b.WriteString("        }\n")
		c.b.WriteString("        err = p.AfterProcess()\n")
		c.b.WriteString("        encoded, err := json.Marshal(p.afterRet)\n")
		c.b.WriteString("        if err != nil {\n")
		c.b.WriteString("            log.Println(os.Stderr, \"输出编码失败: %v\\n\", err)\n")
		c.b.WriteString("            os.Exit(1)\n")
		c.b.WriteString("        }\n")
		c.b.WriteString("        log.Println(string(encoded))\n")
		c.b.WriteString("        return err\n")
	} else {
		c.b.WriteString("        return []string{result}, err\n")
	}
	c.b.WriteString("        }\n")
	c.b.WriteString("    }\n")
	return nil
}
func (c *CodeBuilder) buildExecuteDir() error {
	c.b.WriteString("\nfunc (p *" + c.fileName + ") run() error { \n")
	c.b.WriteString("    var err error\n")
	c.b.WriteString("    err=p.ValidateInput(p.currentData)\n")
	c.b.WriteString("    if err!=nil {\n")
	c.b.WriteString("    \treturn err\n")
	c.b.WriteString("    }\n")

	//before
	if strings.TrimSpace(c.promptNode.BeforeCode[0]) != "" {
		c.b.WriteString("    p.currentData, err = p.Before(p.currentData)\n")
		c.b.WriteString("    if err!=nil {\n")
		c.b.WriteString("    \tlog.Println(os.Stderr, \"预处理失败 %v\", err)\n")
		c.b.WriteString("    \tos.Exit(1)\n")
		c.b.WriteString("    }\n")
	}
	c.b.WriteString("    sys := p.GenSys(p.currentData)\n")
	c.b.WriteString("    user := p.GenUser(p.currentData)\n")

	c.b.WriteString("    modelConfig := config.GetModelConfig(p.modelname)\n")
	c.b.WriteString("    llm := service.NewLLMClient(*modelConfig)\n")

	c.b.WriteString("    if modelConfig.Stream  {\n")
	c.b.WriteString("        // 流式模式，直接输出，不做 JSON 解析\n")
	c.b.WriteString("        _, err := llm.GeneratePromptResponse(sys, user, true)\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(os.Stderr, \"调用大模型失败: %v\\n\", err)\n")
	c.b.WriteString("            os.Exit(1)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        return nil\n")
	c.b.WriteString("    } else {\n")
	c.b.WriteString("        // 非流式模式，拿完整结果再处理\n")
	c.b.WriteString("        p.modelRet, err = llm.GeneratePromptResponse(sys, user, false)\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(\"调用大模型失败: \", err)\n")
	c.b.WriteString("            os.Exit(1)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        p.FixProcess()\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(\"数据修复失败:\", err)\n")
	c.b.WriteString("            os.Exit(1)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        err = p.AfterProcess()\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(\"数据后处理失败\", err)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        // log.Println(\"p.afterRet\", p.afterRet)\n")
	c.b.WriteString("        encoded, err := json.Marshal(p.afterRet)\n")
	c.b.WriteString("        if err != nil {\n")
	c.b.WriteString("            log.Println(\"输出编码失败:\", err)\n")
	c.b.WriteString("            os.Exit(1)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        log.Println(string(encoded))\n")
	c.b.WriteString("        return err\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) buildSingleMain() error {
	c.b.WriteString("func main() {\n")
	c.b.WriteString("    p := New" + c.fileName + "()\n")
	c.b.WriteString("    p.init()\n")
	c.b.WriteString("    p.loadInput()\n")
	c.b.WriteString("    p.parsedata()\n")
	c.loopRange()
	c.b.WriteString("    for _, item := range p.Input {\n")
	c.b.WriteString("        p.currentData = item\n")
	c.b.WriteString("        err:=p.runWithRetry(3)\n")
	c.b.WriteString("        if err!=nil{\n")
	c.b.WriteString("        \tlog.Println(\"p.run失败：\",err)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        p.writeOut(p.afterRet)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) buildLoopMain() error {
	c.b.WriteString("func main() {\n")
	c.b.WriteString("\tp := NewGetpath()\n")
	c.b.WriteString("\tp.init()\n")
	c.b.WriteString("\tp.loadInput()\n")
	c.b.WriteString("\tp.parsedata()\n")
	c.b.WriteString("\tpath := \"" + c.promptNode.iteraterPath + "\"\n")
	c.loopRange()
	c.b.WriteString("\tfor _, item := range p.Input {\n")
	c.b.WriteString("\t\tp.currentData = item\n")
	c.b.WriteString("\t\t// 将路径拆分成每一层\n")
	c.b.WriteString("\t\tparts := strings.Split(path, \".\")\n")
	c.b.WriteString("\t\tp.it_idx = 0\n")
	c.b.WriteString("\t\t// 遍历路径，最后一层循环处理\n")
	c.b.WriteString("\t\terr := p.traversePath(reflect.ValueOf(item), parts, func(e reflect.Value) {\n")
	c.b.WriteString("\t\t\t// 类型断言到最终元素类型\n")
	c.b.WriteString("\t\t\tsubItem, ok := e.Interface().(" + c.loopClass + ")\n")
	c.b.WriteString("\t\t\tif !ok {\n")
	c.b.WriteString("\t\t\t\tlog.Println(\"类型断言失败:\", e.Type())\n")
	c.b.WriteString("\t\t\t\treturn\n")
	c.b.WriteString("\t\t\t}\n")
	c.b.WriteString("\t\t\tp.it = subItem\n")
	c.b.WriteString("\t\t\tif err := p.runWithRetry(3); err != nil {\n")
	c.b.WriteString("\t\t\t\tlog.Println(\"p.run失败：\", err)\n")
	c.b.WriteString("\t\t\t}\n")
	c.b.WriteString("\t\t\tp.it_idx++\n")
	c.b.WriteString("\t\t})\n")
	c.b.WriteString("\t\tif err != nil {\n")
	c.b.WriteString("\t\t\tlog.Println(\"路径遍历失败:\", err)\n")
	c.b.WriteString("\t\t}\n")
	c.b.WriteString("\t\tp.writeOut(p.afterRet)\n")
	c.b.WriteString("\t}\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) buildSingleLExecute() error {
	c.b.WriteString("func (p *"+c.fileName+") singleExecute() {\n")
	
	c.b.WriteString("\t// 将路径拆分成每一层\n")
	c.b.WriteString("\tparts := strings.Split(p.path, \".\")\n")
	c.b.WriteString("\tp.it_idx = 0\n")
	c.b.WriteString("\t\t// 遍历路径，最后一层循环处理\n")
	c.b.WriteString("\t\terr := p.traversePath(reflect.ValueOf(p.currentData), parts, func(e reflect.Value) {\n")
	c.b.WriteString("\t\t\t// 类型断言到最终元素类型\n")
	c.b.WriteString("\t\t\tsubItem, ok := e.Interface().(" + c.loopClass + ")\n")
	c.b.WriteString("\t\t\tif !ok {\n")
	c.b.WriteString("\t\t\t\tlog.Println(\"类型断言失败:\", e.Type())\n")
	c.b.WriteString("\t\t\t\treturn\n")
	c.b.WriteString("\t\t\t}\n")
	c.b.WriteString("\t\t\tp.it = subItem\n")
	c.b.WriteString("\t\t\tif err := p.runWithRetry(3); err != nil {\n")
	c.b.WriteString("\t\t\t\tlog.Println(\"p.run失败：\", err)\n")
	c.b.WriteString("\t\t\t}\n")
	c.b.WriteString("\t\t\tp.it_idx++\n")
	c.b.WriteString("\t\t})\n")
	c.b.WriteString("\t\tif err != nil {\n")
	c.b.WriteString("\t\t\tlog.Println(\"路径遍历失败:\", err)\n")
	c.b.WriteString("\t\t}\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) buildSingleExecute() error {
	c.b.WriteString("func (p *"+c.fileName+") singleExecute() {\n")
	c.b.WriteString("\terr := p.runWithRetry(3)\n")
	c.b.WriteString("\tif err != nil {\n")
	c.b.WriteString("\t\tlog.Println(\"p.run失败：\", err)\n")
	c.b.WriteString("\t}\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) buildExeSingleMain() error {
	c.b.WriteString("func main() {\n")
	c.b.WriteString("    p := New" + c.fileName + "()\n")
	c.b.WriteString("    p.init()\n")
	c.b.WriteString("    p.loadInput()\n")
	c.b.WriteString("    // 执行 abc.exe 拆解 input\n")
	c.b.WriteString("    if err := p.runexe(\"" + c.promptNode.RunExe[0] + "\"); err != nil {\n")
	c.b.WriteString("        fmt.Println(\"❌ " + c.promptNode.RunExe[0] + " 执行失败\", err)\n")
	c.b.WriteString("        return\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    p.loadInput()\n")
	c.b.WriteString("    p.parsedata()\n")
	c.loopRange()
	c.b.WriteString("    for _, item := range p.Input {\n")
	c.b.WriteString("        p.currentData = item\n")
	c.b.WriteString("        err:=p.run()\n")
	c.b.WriteString("        if err!=nil{\n")
	c.b.WriteString("        \tlog.Println(\"p.run失败：\",err)\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        p.writeOut(p.afterRet)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    p.runexe(\"" + c.promptNode.RunExe[1] + "\")\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) writeExeRuner() error {
	c.b.WriteString("func (p *" + c.fileName + ") runexe(exeName string) error {\n")
	c.b.WriteString("    exePath, err := os.Executable()\n")
	c.b.WriteString("    if err != nil {\n")
	c.b.WriteString("        log.Fatalf(\"获取可执行文件路径失败: %v\", err)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    exeDir := filepath.Dir(exePath)\n")
	c.b.WriteString("    exeName= filepath.Join(exeDir, exeName)\n\n")
	c.b.WriteString("    cmd := exec.Command(exeName, p.inputfile)\n")
	c.b.WriteString("    output, err := cmd.CombinedOutput()\n")
	c.b.WriteString("    if err != nil {\n")
	c.b.WriteString("        return fmt.Errorf(\"执行 %s 失败: %v, 输出: %s\", exeName, err, string(output))\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    log.Printf(\"%s 执行完成，输出: %s\", exeName, string(output))\n")
	c.b.WriteString("    return nil\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) looppath() error {
	c.b.WriteString("func(p *" + c.fileName + ") traversePath(v reflect.Value, parts []string, handle func(reflect.Value)) error {\n")
	c.b.WriteString("    if len(parts) == 0 {\n")
	c.b.WriteString("        // 最后一层必须是 slice\n")
	c.b.WriteString("        v = reflect.Indirect(v)\n")
	c.b.WriteString("        if v.Kind() != reflect.Slice && v.Kind() != reflect.Array {\n")
	c.b.WriteString("            return fmt.Errorf(\"最后一层不是切片类型: %s\", v.Kind())\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        for i := 0; i < v.Len(); i++ {\n")
	c.b.WriteString("            handle(v.Index(i))\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        return nil\n")
	c.b.WriteString("    }\n\n")

	c.b.WriteString("    v = reflect.Indirect(v)\n\n")

	c.b.WriteString("    switch v.Kind() {\n")
	c.b.WriteString("    case reflect.Struct:\n")
	c.b.WriteString("        f := v.FieldByName(strings.Title(parts[0]))\n")
	c.b.WriteString("        if !f.IsValid() {\n")
	c.b.WriteString("            return fmt.Errorf(\"字段 %s 不存在\", parts[0])\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        return p.traversePath(f, parts[1:], handle)\n")
	c.b.WriteString("    case reflect.Slice, reflect.Array:\n")
	c.b.WriteString("        for i := 0; i < v.Len(); i++ {\n")
	c.b.WriteString("            elem := v.Index(i)\n")
	c.b.WriteString("            if err := p.traversePath(elem, parts, handle); err != nil {\n")
	c.b.WriteString("                return err\n")
	c.b.WriteString("            }\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        return nil\n")
	c.b.WriteString("    default:\n")
	c.b.WriteString("        return fmt.Errorf(\"无法遍历字段 %s, 类型: %s\", parts[0], v.Kind())\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) buildReTry() error {
	c.b.WriteString("func (p *" + c.fileName + ") runWithRetry(maxRetries int) error {\n")
	c.b.WriteString("    var err error\n")
	c.b.WriteString("    for attempt := 1; attempt <= maxRetries; attempt++ {\n")
	c.b.WriteString("        err = p.run()\n")
	c.b.WriteString("        if err == nil {\n")
	c.b.WriteString("            return nil\n")
	c.b.WriteString("        }\n")
	c.b.WriteString("        log.Printf(\"调用模型失败，第 %d 次重试: %v\", attempt, err)\n")
	c.b.WriteString("        time.Sleep(time.Second * 2)\n")
	c.b.WriteString("    }\n")
	c.b.WriteString("    return fmt.Errorf(\"调用模型失败，已重试 %d 次仍然出错: %v\", maxRetries, err)\n")
	c.b.WriteString("}\n")
	return nil
}
func (c *CodeBuilder) combineSingleCode() error {
	if err := c.isArray(); err != nil {
		return err
	}

	if err := c.writeGeneratedHeader(); err != nil {
		return err
	}
	if err := c.buildImport(); err != nil {
		return err
	}
	if err := c.buildstruct(); err != nil {
		return err
	}
	if err := c.writeNew(); err != nil {
		return err
	}
	if err := c.writeInit(); err != nil {
		return err
	}
	if err := c.writeLoadInput(); err != nil {
		return err
	}

	if err := c.writeParseData(); err != nil {
		return err
	}
	if err := c.buildWriteOut(); err != nil {
		return err
	}

	if err := c.genModelPrompt(); err != nil {
		return err
	}
	if err := c.ifModel(); err != nil {
		return err
	}
	if err := c.writeBefore(); err != nil {
		return err
	}
	if err := c.writeAfter(); err != nil {
		return err
	}
	if err := c.writeFix(); err != nil {
		return err
	}
	if err := c.buildIsValid(); err != nil {
		return err
	}
	if err := c.buildReTry(); err != nil {
		return err
	}
	if strings.TrimSpace(c.promptNode.FixCode[0]) == "" && strings.TrimSpace(c.promptNode.AfterCode[0]) == "" {
		if err := c.buildExecuteDir(); err != nil {
			return err
		}
	} else {
		if err := c.buildExecutePipeline(); err != nil {
			return err
		}
	}
	//如果有iterater则增加循环内容，调用循环main
	if c.promptNode.iteraterPath != "" {
		if err := c.looppath(); err != nil {
			return err
		}
		if err := c.buildLoopMain(); err != nil {
			return err
		}
		return nil
	}
	//如果有runexe则main先执行exe转input
	if len(c.promptNode.RunExe) != 0 {
		if err := c.writeExeRuner(); err != nil {
			return err
		}
		if err := c.buildExeSingleMain(); err != nil {
			return err
		}
	} else {
		if err := c.buildSingleMain(); err != nil {
			return err
		}
	}
	return nil
}
func (c *CodeBuilder) WcombineSingleCode() error {
	if err := c.isArray(); err != nil {
		return err
	}

	if err := c.writeGeneratedHeader(); err != nil {
		return err
	}
	if err := c.buildImport(); err != nil {
		return err
	}
	if err := c.buildstruct(); err != nil {
		return err
	}
	if err := c.writeNew(); err != nil {
		return err
	}
	if err := c.writeInit(); err != nil {
		return err
	}
	if err := c.writeLoadInput(); err != nil {
		return err
	}

	if err := c.writeParseData(); err != nil {
		return err
	}
	if err := c.buildWriteOut(); err != nil {
		return err
	}

	if err := c.genModelPrompt(); err != nil {
		return err
	}
	if err := c.ifModel(); err != nil {
		return err
	}
	if err := c.writeBefore(); err != nil {
		return err
	}
	if err := c.writeAfter(); err != nil {
		return err
	}
	if err := c.writeFix(); err != nil {
		return err
	}
	if err := c.buildIsValid(); err != nil {
		return err
	}
	if err := c.buildReTry(); err != nil {
		return err
	}
	if strings.TrimSpace(c.promptNode.FixCode[0]) == "" && strings.TrimSpace(c.promptNode.AfterCode[0]) == "" {
		if err := c.buildExecuteDir(); err != nil {
			return err
		}
	} else {
		if err := c.buildExecutePipeline(); err != nil {
			return err
		}
	}
	//如果有iterater则增加循环内容，调用循环execute
	if c.promptNode.iteraterPath != "" {
		if err := c.looppath(); err != nil {
			return err
		}
		if err := c.buildSingleLExecute(); err != nil {
			return err
		}
		return nil
	}else {
		if err := c.buildSingleExecute(); err != nil {
			return err
		}
	}
	return nil
}
func (c *CodeBuilder) TcombineSingleCode() error {
	if err := c.isArray(); err != nil {
		return err
	}
	if err := c.writeGeneratedHeader(); err != nil {
		return err
	}
	if err := c.buildstruct(); err != nil {
		return err
	}
	return nil
}
func (c *CodeBuilder) loopRange() error {
	if len(c.promptNode.loopRange) == 1 {
		c.b.WriteString("    p.Input= p.Input[0 : " + strconv.Itoa(c.promptNode.loopRange[0]) + "]\n")
		return nil
	}
	if len(c.promptNode.loopRange) == 2 {
		c.b.WriteString("    p.Input= p.Input[" + strconv.Itoa(c.promptNode.loopRange[0]) + "-1 : " + strconv.Itoa(c.promptNode.loopRange[1]) + "]\n")
		return nil
	}
	return nil
}
func Generatworkflow(pkgName string) string {
	var b strings.Builder

	// 写文件头注释和包名
	b.WriteString("// Code generated by PromptDSL.\n")
	b.WriteString("package main\n\n")

	// import 区块
	b.WriteString("import (\n")
	b.WriteString(`	   gen "workflow/generated"` + "\n")
	b.WriteString(")\n")

	// main 函数开始
	b.WriteString("func main() {\n")
	b.WriteString("    //在此组织工作流\n")
	b.WriteString("    //\n")
	b.WriteString("}\n")
	return b.String()
}
