package codegen

import (
	"fmt"
	"regexp"
	"strings"
)

var symbolToImport = map[string]string{
	// 基础功能
	"fmt.":          "fmt",
	"strings.":      "strings",
	"strconv.":      "strconv",
	"bytes.":        "bytes",
	"math.":         "math",
	"math/rand.":    "math/rand",
	"time.":         "time",
	"unicode.":      "unicode",
	"unicode/utf8.": "unicode/utf8",
	"json":          "encoding/json",

	// IO 与文件
	"io.":            "io",
	"io/ioutil.":     "io/ioutil", // 旧版兼容，Go 1.16 后用 os.ReadFile 等替代
	"os.":            "os",
	"path.":          "path",
	"path/filepath.": "path/filepath",

	// 网络与编码
	"net.":             "net",
	"net/http.":        "net/http",
	"net/url.":         "net/url",
	"encoding/json.":   "encoding/json",
	"encoding/xml.":    "encoding/xml",
	"encoding/base64.": "encoding/base64",
	"encoding/hex.":    "encoding/hex",

	// 日志与调试
	"log.":      "log",
	"debug/pe.": "debug/pe", // 示例：用于调试工具

	// 并发与同步
	"sync.":        "sync",
	"sync/atomic.": "sync/atomic",
	"context.":     "context",

	// 正则与错误处理
	"regexp.": "regexp",
	"errors.": "errors",

	// 反射与运行时
	"reflect.":       "reflect",
	"runtime.":       "runtime",
	"runtime/debug.": "runtime/debug",

	// 测试（如果是生成测试代码时）
	"testing.": "testing",

	// 数据结构与容器
	"container/list.": "container/list",
	"container/heap.": "container/heap",
}

func Generateprompthandle(root *PromptNode, pkgName string, eval *final, filename string, goimport []goimport) string {
	// fmt.Println("😅")
	if len(root.ModelFields) > 0 {
		fmt.Println("root.ModelFields:", root.ModelFields)
	}

	var b strings.Builder
	outputTypeStr := filename + "OutputContext"
	if root.outputspectNodes.IsArray {
		outputTypeStr = "[]" + filename + "OutputContext"
	}
	if len(root.OutFields) == 0 {
		outputTypeStr = "[]string"
	}
	var model string
	if len(root.ModelFields) > 0 {
		model = filename + "ModelOutputContext"
		if root.outputspectNodes.IsArray {
			model = "[]" + filename + "ModelOutputContext"
		}
	}

	// 写包名和注释
	b.WriteString("// Code generated by PromptDSL. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", "main"))

	//import
	//after+fix
	afterCode := strings.Join(root.AfterCode, "\n")
	fixCode := strings.Join(root.FixCode, "\n")
	beforeCode := strings.Join(root.BeforeCode, "\n")

	allCode := afterCode + "\n" + fixCode + "\n" + beforeCode
	// renderImportSectionWithAlias()
	pkgs := inferImportsFromCode(allCode)
	//main

	requiredPkgs := []string{"os","log", "fmt", "github.com/along416/promptDSL/service", "github.com/along416/promptDSL/codegen", "github.com/along416/promptDSL/config","encoding/json"}
	if len(root.FixCode) == 0 || len(root.AfterCode) == 0 {
		requiredPkgs = []string{"os","log", "fmt", "github.com/along416/promptDSL/service", "strings", "github.com/along416/promptDSL/config","encoding/json"}
	}
	for _, req := range requiredPkgs {
		has := false
		for _, pkg := range pkgs {
			if pkg == req {
				has = true
				break
			}
		}
		if !has {
			pkgs = append(pkgs, req)
		}
	}
	importBlock := renderImportSectionWithAlias(goimport, pkgs)

	b.WriteString(importBlock)

	// struct

	//sub

	for _, substruct := range root.SubFields {
		b.WriteString("type " + filename + capitalizeFirst(substruct.Name) + " struct {\n")
		for _, field := range substruct.Fields {
			b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", field.Name, field.Type, field.JsonName))
		}
		b.WriteString("}\n\n")
	}
	b.WriteString("type " + filename + " struct {\n")
	b.WriteString("    Input " + filename + "InputContext\n")
	if len(root.OutFields) > 0 {
		b.WriteString("    Output " + filename + "OutputContext\n")
	}

	if len(root.ModelFields) > 0 {
		b.WriteString("    ModelOutput " + filename + "ModelOutputContext\n")
	}
	b.WriteString("}\n\n")
	//InputContext
	b.WriteString("type " + filename + "InputContext struct {\n")
	for _, field := range root.InFields {
		fieldName := capitalizeFirst(field.Name)
		if field.Type == "struct" {
			b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, filename+fieldName, field.JsonName))
			continue
		}
		b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, field.Type, field.JsonName))
	}
	b.WriteString("}\n\n")

	//OutputContext
	if len(root.OutFields) > 0 {
		b.WriteString("type " + filename + "OutputContext struct {\n")
		for _, field := range root.OutFields {
			fieldName := capitalizeFirst(field.Name)
			if field.Type == "struct" {
				b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, filename+fieldName, field.JsonName))
				continue
			}
			b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, field.Type, field.JsonName))
		}
		b.WriteString("}\n\n")
	}

	//if modlefield不为空，则构造modelstruct，并且修改调用函数传参
	if len(root.ModelFields) > 0 {
		b.WriteString("type " + filename + "ModelOutputContext struct {\n")
		for _, field := range root.ModelFields {
			fieldName := capitalizeFirst(field.Name)
			if field.Type == "struct" {
				b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, filename+fieldName, field.JsonName))
				continue
			}
			b.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", fieldName, field.Type, field.JsonName))
		}
		b.WriteString("}\n\n")
	}

	//gensystem
	//写入sys处理逻辑
	b.WriteString(fmt.Sprintf("func (prompt *" + filename + ")GenSys(in " + filename + "InputContext) string {\n"))
	b.WriteString("    var b strings.Builder\n")

	for _, line := range eval.Sys {
		b.WriteString(fmt.Sprintf("    %s\n", line))
	}
	b.WriteString("    return b.String()\n")
	b.WriteString("\n}\n\n")

	//genuser
	b.WriteString(fmt.Sprintf("func (prompt *" + filename + ")GenUser(in " + filename + "InputContext) string {\n"))
	b.WriteString("    var b strings.Builder\n")

	for _, line := range eval.User {
		b.WriteString(fmt.Sprintf("    %s\n", line))
	}
	b.WriteString("    return b.String()\n")
	b.WriteString("\n}\n\n")

	//model or output

	output := outputTypeStr
	var outname string = "output"
	if len(root.ModelFields) > 0 {
		output = model
		outname = "model"
	}

	if strings.TrimSpace(root.AfterCode[0]) != "" {

		b.WriteString(fmt.Sprintf("func (prompt *"+filename+")AfterProcess("+outname+" %s) %s {\n", output, outputTypeStr))
		b.WriteString(root.AfterCode[0])
		b.WriteString("\n}\n\n")
	}

	// 写入 Before 函数（如果有）
	if strings.TrimSpace(root.BeforeCode[0]) != "" {
		b.WriteString(fmt.Sprintf("func (prompt *" + filename + ")Before(in " + filename + "InputContext) (" + filename + "InputContext ,error){\n"))
		b.WriteString(root.BeforeCode[0])
		b.WriteString("\n}\n")
	}

	// 写入 Fix 函数（如果有）
	if len(root.FixCode) > 0 {
		if strings.TrimSpace(root.FixCode[0]) != "" {
			fixauto := "codegen.FixAuto[" + output + "](response)\n"
			re := regexp.MustCompile(`fix-auto`)
			b.WriteString(fmt.Sprintf("func (prompt *"+filename+")FixProcess(response string) (%s ,error){\n", output))
			b.WriteString(re.ReplaceAllString(root.FixCode[0], fixauto))
			b.WriteString("\n}\n")
		}
	}

	// 写入 合法性校验 函数
	b.WriteString(fmt.Sprintf("func (prompt *" + filename + ")ValidateInput(input " + filename + "InputContext) (error){\n"))
	validationCode := GenValidationCodeFromFields(root.InFields, filename)
	b.WriteString(validationCode)
	b.WriteString("    return nil\n}\n")

	// 写 主调用 函数
	b.WriteString("\nfunc (prompt *" + filename + ")" + filename + "(input " + filename + "InputContext,modelname string)  (" + outputTypeStr + ",error) {\n")
	b.WriteString("    fmt.Fprintln(os.Stderr, \"[main] 程序启动，等待输入...\")\n")
	b.WriteString("    var err error\n")
	b.WriteString("    err=prompt.ValidateInput(input)\n")
	b.WriteString("    if err!=nil {\n")
	b.WriteString("    \treturn nil,err\n")
	b.WriteString("    }\n")

	//before
	if strings.TrimSpace(root.BeforeCode[0]) != "" {
		b.WriteString("    input, err = prompt.Before(input)\n")
		b.WriteString("    if err!=nil {\n")
		b.WriteString("    \tfmt.Fprintf(os.Stderr, \"预处理失败 %v\", err)\n")
		b.WriteString("    \tos.Exit(1)\n")
		b.WriteString("    }\n")
	}
	b.WriteString("    sys := prompt.GenSys(input)\n")
	b.WriteString("    user := prompt.GenUser(input)\n")

	b.WriteString("    modelConfig := config.GetModelConfig(modelname)\n")
	b.WriteString("    llm := service.NewLLMClient(*modelConfig)\n")
	b.WriteString("    result, err := llm.GeneratePromptResponse(sys, user)\n")
	b.WriteString("    if err != nil {\n")
	b.WriteString("        fmt.Fprintf(os.Stderr, \"调用大模型失败: %v\\n\", err)\n")
	b.WriteString("        os.Exit(1)\n")
	b.WriteString("    }\n")

	if len(root.OutFields) > 0 {
		b.WriteString("    " + outname + ", err := prompt.FixProcess(result)\n")
		b.WriteString("    if err != nil {\n")
		b.WriteString("        fmt.Fprintf(os.Stderr, \"解析输入 JSON 失败011111: %v\\n\", err)\n")
		b.WriteString("        os.Exit(1)\n")
		b.WriteString("    }\n")
		b.WriteString("    final := prompt.AfterProcess(" + outname + ")\n")
		b.WriteString("    encoded, err := json.Marshal(final)\n")
		b.WriteString("    if err != nil {\n")
		b.WriteString("        fmt.Fprintf(os.Stderr, \"输出编码失败: %v\\n\", err)\n")
		b.WriteString("        os.Exit(1)\n")
		b.WriteString("    }\n")
		b.WriteString("    fmt.Println(string(encoded))\n")
		b.WriteString("    return final,err\n")
	} else {
		b.WriteString("    return []string{result},err\n")
	}

	b.WriteString("}\n")

	//写入main函数
	b.WriteString("\nfunc main(){\n")
	writeMain(&b, filename)
	b.WriteString("}\n")

	return b.String()
}

func writeMain(b *strings.Builder, filename string) {
	b.WriteString("    // 初始化配置和日志\n")
	b.WriteString("    if len(os.Args) < 3 {\n")
	b.WriteString("        log.Fatal(\"请提供输入文件路径和配置路径作为参数\")\n")
	b.WriteString("    }\n")
	b.WriteString("    config.InitConfig(os.Args[2])\n")
	b.WriteString("    config.InitLogger()\n\n")
	b.WriteString("    // 读取输入文件\n")
	b.WriteString("    inputfile := os.Args[1]\n")
	b.WriteString("    data, err := os.ReadFile(inputfile)\n")
	b.WriteString("    if err != nil {\n")
	b.WriteString("        log.Fatalf(\"无法读取文件: %v\", err)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    // 解析输入数据\n")
	b.WriteString("    var prompt " + filename + "\n")
	b.WriteString("    err = json.Unmarshal(data, &prompt.Input)\n")
	b.WriteString("    if err != nil {\n")
	b.WriteString("        log.Fatalf(\"解析输入JSON失败: %v\", err)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    // 调用主处理函数\n")
	b.WriteString("    result, err := prompt." + filename + "(prompt.Input, \"qwen-max\")\n")
	b.WriteString("    if err != nil {\n")
	b.WriteString("        log.Fatalf(\"处理失败: %v\", err)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    // 输出结果\n")
	b.WriteString("    log.Println(\"处理结果:\", result)\n")
	b.WriteString("    // 将结果写入output.json文件\n")
	b.WriteString("    output, err := json.MarshalIndent(result, \"\", \"  \")\n")
	b.WriteString("    if err != nil {\n")
	b.WriteString("        log.Fatalf(\"结果序列化失败: %v\", err)\n")
	b.WriteString("    }\n")
	b.WriteString("    err = os.WriteFile(\"output.json\", output, 0644)\n")
	b.WriteString("    if err != nil {\n")
	b.WriteString("        log.Fatalf(\"写入输出文件失败: %v\", err)\n")
	b.WriteString("    }\n")
	b.WriteString("    log.Println(\"结果已成功写入output.json文件\")\n")
}

func Generatworkflow(pkgName string) string {
	var b strings.Builder

	// 写文件头注释和包名
	b.WriteString("// Code generated by PromptDSL.\n")
	b.WriteString("package main\n\n")

	// import 区块
	b.WriteString("import (\n")
	b.WriteString(`	   gen "workflow/generated"` + "\n")
	b.WriteString(")\n")

	// main 函数开始
	b.WriteString("func main() {\n")
	b.WriteString("    //在此组织工作流\n")
	b.WriteString("    //\n")
	b.WriteString("}\n")
	return b.String()
}
func GenValidationCodeFromFields(fields []FieldDef, filename string) string {
	var b strings.Builder
	// fmt.Println("derived:👀")
	for _, f := range fields {
		// 如果包含 "derived" 注解，则跳过校验
		skip := false
		for _, ann := range f.Annotations {
			// fmt.Println("derived:👀", ann)
			if ann == "derived" {
				skip = true
				break
			}
		}
		if skip {
			continue
		}

		switch f.Type {
		case "string":
			b.WriteString(fmt.Sprintf(
				"\tif input.%s == \"\" {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, filename, f.Name))
		case "struct":
			b.WriteString(fmt.Sprintf(
				"\tif input.%s == ("+filename+"%s{}) {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, f.Name, f.Name))
		case "int", "int32", "int64", "float32", "float64":
			b.WriteString(fmt.Sprintf(
				"\tif input.%s == 0 {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, f.Name))
		case "[]string", "[]int", "[]float64", "map[string]string":
			b.WriteString(fmt.Sprintf(
				"\tif len(input.%s) == 0 {\n\t\treturn fmt.Errorf(\"%sInputContext:%s 不能为空\")\n\t}\n",
				f.Name, f.Name))
		}
	}

	return b.String()
}
