package wcodegen

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strings"

	Wparser "github.com/ycstella/prompt-dsl/codegen/Wparser"
)

type Generater struct {
	astNode   *TaskNode
	topResult []*TaskNode
	structs   string
	funcs     string
	exec      string
	fullCode  string
	importstr string
	ctx *Wparser.WorkflowContext
}

func NewwcodeGener(astNode *TaskNode, topResult []*TaskNode, ctx *Wparser.WorkflowContext) Generater {
	return Generater{
		astNode:   astNode,
		topResult: topResult,
		ctx:ctx,
	}
}

// 变量管理
func (g *Generater) assignNames() (err error) {
	counter := 1
	for _, n := range g.topResult {
		// 给每个节点一个唯一变量名
		n.VarName = fmt.Sprintf("v%d", counter)
		counter++

		// 根据类型决定函数名
		switch n.Type {
		case Func:
			n.CallName = extractFuncName(n.Expr)
		case Arithmetic:
			n.CallName = fmt.Sprintf("Arith_%d", counter)
		case Conditional:
			n.CallName = fmt.Sprintf("Conditional_%d", counter)
		case Atom:
			n.CallName = n.Expr
		case FAtom:
			filed := getLastPart(n.Expr)
			if len(n.Dependencies) > 0 {
				depId := n.Dependencies[0].Id
				depVar := findVarNameById(depId, g.topResult)
				n.CallName = depVar + "." + filed
			} else {
				n.CallName = filed
			}

		}

	}
	return err
}

func (g *Generater) genImport() string {
	return `
package main
import (
	"log"
	"github.com/ycstella/prompt-dsl/codegen"
)`
}
func (g *Generater) genStructs() string {
	w:=BuildModel(g.ctx)
	structcode := GenerateCode(w)
	return structcode
}
//直连单个task的调用
func (g *Generater) genFuncs() string {
	
	const tmplStr = `
{{- range .}}
	{{- if eq .Type 2 }}  
func {{ .CallName }}(
	{{- range $j, $d := .Dependencies }}
		{{- if $j}}, {{ end }}{{ findVarNameById $d.Id $ }} any
	{{- end }}) {{.ReturnType}} {
	return {{ range $j, $d := .Dependencies }}
	{{- if $j}} * {{ end }}{{ findVarNameById $d.Id $ }}
	{{- end }}
}
	{{- else if eq .Type 1 }}  
func W{{ .CallName }}(
	{{- range $j, $d := .Dependencies }}
		{{- if $j}}, {{ end }}{{ findVarNameById $d.Id $ }}
	{{- end }} any) {{.ReturnType}} { 
	task:= New{{ .CallName }}()
	task.init()
	err := codegen.CopyStructRecursive(&{{- range $j, $d := .Dependencies }}
		{{- if $j}}, {{ end }}{{ findVarNameById $d.Id $ }}
	{{- end }}.afterRet,&task.currentdata)
	if err != nil {
		log.Fatal(err)
	}
	task.singleExecute()
		return task.afterRet
	}
	{{- else if eq .Type 3 }}  
func {{ .CallName }}(
	{{- range $j, $d := .Dependencies }}
		{{- if $j}}, {{ end }}{{ findVarNameById $d.Id $ }}
	{{- end }} any) any { return nil }
	{{- end}}

{{- end }}
`

	funcStr := renderTemplateWithLookup(g.topResult, tmplStr)
	return funcStr
}
func (g *Generater) genFieldAssignments(node *TaskNode, parentPath string) string {
	var sb strings.Builder
	fieldPath := "out"
	if parentPath != "" {
		fieldPath = parentPath + "." + node.Id
	} else if node.Id != "" {
		fieldPath = node.Id
	}

	for _, value := range g.topResult {
		if value.Expr != "" && value.Type == Field && node.Id == value.Id {
			sb.WriteString(fmt.Sprintf("\t%s = %s\n", fieldPath, value.Dependencies[0].VarName))
		} else if value.Expr != "" && value.Type == SubField && node.Id == value.Id {
			sb.WriteString(fmt.Sprintf("\t%s = %s.%s\n", fieldPath, value.Dependencies[0].VarName, node.Id))
		}
	}

	// 递归赋值子节点
	for _, child := range node.Children {
		sb.WriteString(g.genFieldAssignments(child, fieldPath))
	}

	return sb.String()
}

func (g *Generater) genExec() string {
	var b strings.Builder
	const topStr = `
	// 拓扑排序执行
	{{- $length := len . -}}
	{{- range $i, $n := . }}
		{{- if or (eq $n.Type 2) (eq $n.Type 3) (eq $n.Type 1) }}
		{{ $n.VarName }} := W{{ $n.CallName }}(
			{{- range $j, $d := $n.Dependencies }}
				{{- if $j}}, {{ end }}{{ findVarNameById $d.Id $ }}
			{{- end }})
		{{- else if eq $n.Type 5 }}
		{{ $n.VarName }} := {{ $n.CallName }}
		 {{- else if eq $n.Type 7 }}
		{{ $n.VarName }} := {{ $n.CallName }}
		{{- end }}
	{{- end }}
`

	//暴力遍历model，赋值out的每一个字段（有expr的通过id匹配map，取其varname）,递归遍历其子字段，子字段的赋值在其父字段之后

	feilds := g.genFieldAssignments(g.astNode, "")
	log.Println("进入字段赋值")
	const fieldtpStr2 = `
	//字段赋值
	var out Out
`
	fieldCode2 := renderTemplateWithLookup(g.topResult, fieldtpStr2)
	topCode := renderTemplateWithLookup(g.topResult, topStr)

	b.WriteString("func Run(in1 in1) Out {\n")
	b.WriteString("    // 执行依赖计算\n")

	b.WriteString(topCode)
	b.WriteString(fieldCode2 + feilds)

	b.WriteString("\n")
	b.WriteString(`
    return out
}
`)

	return b.String()
}
// 单部分获取
func (g *Generater) generateCodeSingle() (err error) {
	g.assignNames()
	g.importstr=g.genImport()
	g.structs = g.genStructs()
	g.funcs = g.genFuncs()
	g.exec = g.genExec()
	return err
}

// 组装所有内容
func (g *Generater) combine() (err error) {
	g.fullCode = fmt.Sprintf(`// Code generated by WorkflowDSL Generator. DO NOT EDIT.
%s

%s

%s

%s
`,g.importstr, g.structs, g.funcs, g.exec)

	// 确保目录存在
	os.MkdirAll("generated", 0755)
	err = ioutil.WriteFile("generated/workflowSmp.go", []byte(g.fullCode), 0666)
	if err != nil {
		log.Print(err)
	}
	fmt.Println("==== STRUCTS ====\n", g.structs)
	fmt.Println("==== FUNCS ====\n", g.funcs)
	fmt.Println("==== EXEC ====\n", g.exec)

	return err
}
func (g *Generater) Execute() (err error) {
	err = g.generateCodeSingle()
	if err != nil {
		return err
	}
	err = g.combine()
	if err != nil {
		return err
	}
	return err
}
