// Code generated by PromptDSL.
package main

import (
	// "fmt"
	"encoding/json"
	"io/ioutil"
	"log"
	"os"
	gen "workflow/generated"
)

func main() {
	//在此组织工作流
	inputfile := os.Args[1]
	// 读取文件内容
	data, err := ioutil.ReadFile(inputfile)
	if err != nil {
		log.Fatalf("无法读取文件: %v", err)
	}
	
	var prompt gen.SplitSolutionSteps
	err = json.Unmarshal([]byte(data), &prompt.Input)
	if err != nil {
		log.Println(err)
	}
	
	ret1, err :=  prompt.SplitSolutionSteps(prompt.Input)
	if err != nil {
		log.Println(err)
	}
	// ret2:=gen.CheckAndCompleteStepConditions(ret1)
	log.Println(ret1)
}
