// Code generated by PromptDSL.
package main

import (
	// "fmt"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	gen "workflow/generated"
)

func main() {
	//在此组织工作流
	inputfile := os.Args[1]
	// 读取文件内容
	data, err := ioutil.ReadFile(inputfile)
	if err != nil {
		log.Fatalf("无法读取文件: %v", err)
	}
	var prompt2 gen.SplitSolutionSteps
	err = json.Unmarshal([]byte(data), &prompt2.Input)
	if err != nil {
		log.Println(err)
	}
	ret2, err2 :=  prompt2.SplitSolutionSteps(prompt2.Input)
	if err != nil {
		log.Println("ret2:",err2)
	}
	fmt.Println("ret2:",ret2)
	var prompt gen.MdSolutionSteps
	err = json.Unmarshal([]byte(data), &prompt.Input)
	if err != nil {
		log.Println(err)
	}
	
	ret1, err :=  prompt.MdSolutionSteps(prompt.Input)
	if err != nil {
		log.Println(err)
	}
	log.Println(ret1)
	
	// ret2:=gen.CheckAndCompleteStepConditions(ret1)
	
}
